blog/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.home, name="home"),
    path("detail/<int:blog_id>/", views.detail, name="detail"),
    path("new/", views.new, name="post_new"),
    path("edit/<int:blog_id>/", views.edit, name="edit"),
    path("delete/<int:blog_id>/", views.remove, name="delete"),
    path("comment_edit/<int:comment_id>/", views.comment_edit, name="comment_edit"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
    path("hashtag/", views.hashtagform, name="hashtag"),
    path("search/<int:hashtag_id>", views.search, name="search"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    image = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    comment_text = models.CharField(max_length=50)

    def __str__(self):
        return self.comment_text

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Blog, Comment, Hashtag

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','body', 'hashtags', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from .forms import BlogForm, CommentForm, HashtagForm
from .models import Blog, Comment, Hashtag
# Create your views here.

def home(request):
    blogs = Blog.objects.all()
    hashtags = Hashtag.objects
    return render(request, 'blog/home.html', {'blogs':blogs, 'hashtags':hashtags})

def blogform(request, blog_id=None):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES, instance=blog_id)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.title = form.cleaned_data["title"]
            blog.body = form.cleaned_data["body"]
            blog.pub_date = timezone.now()
            blog.save()
            form.save_m2m()
            return redirect('blog:detail', blog.id)
    else:
        form = BlogForm(instance=blog_id)
        return render(request, 'blog/new.html', {'form':form})

def new(request):
    return blogform(request)

def edit(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return blogform(request, blog)

def remove(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    blog.delete()
    return redirect('blog:home')

def detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.comment_text = form.cleaned_data["comment_text"]
            comment.save()
            return redirect("blog:detail", blog_id)
    else:
        form = CommentForm()
        return render(request, "blog/detail.html", {"blog":blog, "form": form})

def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect("blog:detail", comment.blog.id)


def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    blog = comment.blog
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_text = form.cleaned_data["comment_text"]
            comment.save()
            return redirect("blog:detail", blog.id)
    else:
        form = CommentForm(instance=comment)
        return render(request, "blog/new.html", {"form": form})

def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
                hashtag = form.save(commit=False)
                if Hashtag.objects.filter(name=form.cleaned_data['name']):
                    form = HashtagForm()
                    error_message = "이미 존재하는 해시태그입니다."
                    return render(request, 'blog/hashtag.html', {'form': form, "error_message": error_message})
                else:
                    hashtag.name = form.cleaned_data['name']
                    hashtag.save()
                    return redirect('blog:home')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'blog/hashtag.html', {'form': form})

def search(request, hashtag_id):
        hashtag = get_object_or_404(Hashtag, id=hashtag_id)
        return render(request, 'blog/search.html', {'hashtag': hashtag})

blog/templates/blog/detail.html
{% extends 'index.html' %}

{% block content %}
    <div>
        <div>
                {% if blog.image %}
                    <div class="card" style="width: 18rem;">
                    <img src="{{ blog.image.url }}" class="card-img-top" alt="image1">
                {% endif %}
                        <div class="card-body">
                        </div>
                </div>

            <h1>{{ blog.title }}</h1>
            <p>{{ blog.body }}</p>
            <hr>
            <p>만든 날짜: {{ blog.pub_date }}</p>
            {% for hashtag in blog.hashtags.all %}
            <span>{{ hashtag.name }}</span>
            {% endfor %}
            <hr>
            <a class="btn btn-secondary" href="{% url 'blog:edit' blog.id %}" role="button">수정</a>
            <a class="btn btn-danger" href="{% url 'blog:delete' blog.id %}" role="button">삭제</a>
            <a class="btn btn-danger" href="{% url 'blog:home' %}" role="button">홈으로</a>
        </div>
        {% for comment in blog.comments.all %}
            <div>
                <div>
                    <h3>{{ comment.comment_text }}</h3>
                    <a class="btn btn-secondary" href="{% url 'blog:comment_edit' comment.id %}" role="button">수정</a>
                    <a class="btn btn-danger" href="{% url 'blog:comment_delete' comment.id %}" role="button">삭제</a>
                </div>
            </div>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

blog/templates/blog/edit.html
{% extends 'index.html' %}
{% load staticfiles%}

{% block content %}

  {% for blog in blogs.all %}
    <div class="card">
      <h5>{{ blog.title }}</h5>
      <div class="body">
        <form method="POST">
         {% csrf_token %}
            {{form.as_table}}
        <button type = "submit" class="btn-default">Save</button>
        </form>
      </div>
    </div>
  {% endfor %}

{% endblock %}

blog/templates/blog/hashtag.html
{% extends 'index.html' %}

{% block content %}
<div>
    <div>
        {{ error_message }}
        <form method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'index.html' %}

{% block content %}
    {% if blogs %}
        <table style="text-align: center;">
            <thead>
            <tr>
                <th scope="col" style="width: 10%;">글 번호</th>
                <th scope="col" style="width: 20%;">날짜</th>
                <th scope="col" style="width: 20%;">제목</th>
                <th scope="col" style="width: 50%;">내용</th>
            </tr>
            </thead>
            <tbody>
            {% for blog in blogs %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ blog.pub_date }}</td>
                    <td><a href="{% url 'blog:detail' blog.id %}">{{ blog.title | truncatechars:10 }}</a></td>
                    <td>{{ blog.body | truncatechars:30 }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    <a class="btn btn-secondary" href="{% url 'blog:post_new'%}" role="button">게시글 작성</a>
    <a class="btn btn-secondary" href="{% url 'blog:hashtag'%}" role="button">해시태그 추가</a>
{% endblock %}

blog/templates/blog/new.html
{% extends 'index.html' %}
{% load staticfiles%}

{% block content %}

    <div class="card">
        <h5>{{ blog.title }}</h5>
        <div class="body">
            <form method = 'POST' enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>    
            <input class="btn btn-dark" type="submit" value="제출하기">
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'index.html' %}

{% block content %}
<!-- Main Content -->
<div>
  <div>
    <div>
    {% for blog in hashtag.blog_set.all %}
      <div>
        <a href="{% url 'blog:detail' blog.id %}">
          <h2>
            {{ blog.title }}
          </h2>
          <h3>
            {{ blog.summary }}
          </h3>
        </a>
        <p>
          {{ blog.pub_date }}</p>
      </div>
      <hr>
      {% endfor %}
{% endblock %}

crud/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>:::::::::멋사 정민혁::::::::::</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">LIKE LION</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'blog:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Notice Board</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">Hello, World!</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5">LIKE LION 7th</p>
          <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
        </div>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section class="page-section bg-primary" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">We've got what you need!</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
          <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
        </div>
      </div>
    </div>
  </section>

  <!-- Services Section -->
  <section class="page-section" id="services">
    <div class="container">
      <h2 class="text-center mt-0">Notice Board</h2>
      <hr class="divider my-4">
      <span style="margin-left: 525px">
      </span>
      <div>
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Let's Get In Touch!</h2>
          <hr class="divider my-4">
          <p class="text-muted mb-5">Ready to start your next project with us? Give us a call or send us an email and we will get back to you as soon as possible!</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+1 (202) 555-0149</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:contact@yourwebsite.com">tlsfkaus4862@likelion.org</a>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="small text-center text-muted">Copyright &copy; 2019 - LIKE LION</div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/creative.min.js' %}"></script>

</body>

</html>